# Logout
logout:
    path: /logout

# Dashboard (Inicio)
dashboard:
    path: /
    controller: App\Controller\DashBoardController::index

# Almacenes
almacenes:
    resource: 'routes/almacenes.yaml'
    prefix: /almacenes

